language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
      - pandoc
      - curl
      - jq
before_install:
  - uname -a
  - lsb_release -a
install:
  - for TRY in $(seq 5); do PANDOC_META=$(curl --retry 5 https://api.github.com/repos/jgm/pandoc/releases/latest); [ -z "$PANDOC_META" ] || break; sleep 10; done; [ -n "$PANDOC_META" ] || exit 1
  - PANDOC_URL=$(echo "$PANDOC_META" | jq -r '.assets[] | select(.name|contains(".deb")) | .browser_download_url')
  - curl -Lo pandoc.deb $PANDOC_URL
  - dpkg-deb -x pandoc.deb pandoc
  - export PATH=$(readlink -f pandoc/usr/bin):$PATH
  - pandoc --version
  - pip install pytest>=2.7.3 --upgrade
script:
  - ./clone_avro_and_build.sh --static
  - ./run_benchmark.sh
deploy:
  provider: pypi
  user: byhiras
  password:
    secure: CfVBR3pgujGwx6mwsyzeu87cipl65/UIeePg2kFHlzPUjWw8Ob+224XGcwWeNxZnhahaYiwStZyE1Us/oKxpdJjKnH8k6WrOe/0AB3nPoYAlXnx1F+RfLOEw0QLYGfUDo8fXlkOkJ3SdzzUmgKgcupGtoHtMVkmdTUF0gxwDOoU=
  distributions: "sdist bdist_egg"
  on:
    tags: true
